use hello_world;
db.dropDatabase();

db.hellos.insertMany([
  {name: "France", hello: "bonjour"},
  {name: "Spain", hello: "hola"},
  {name: "Germany", hello: "guten tag"},
  {name: "Netherlands", hello: "Hallo"},
  {name: "Ukraine", hello: "Dobriy den"},
  {name: "Portugal", hello: "Olá"},
  {name: "Denmark", hello: "Hej"},
  {name: "Estonia", hello: "Tere"},
  {name: "Italy", hello: "Ciao"},
  {name: "Slovakia", hello: "Ahoj"},
  {name: "Bulgaria", hello: "Zdraveĭte"},
  {name: "Iceland", hello: "Góðan dag"},
  {name: "Hungary", hello: "Jó napot"},
  {name: "Greece", hello: "Geia sas"},
  {name: "Lithuania", hello: "Sveiki"},
  {name: "Finland", hello: "Hei"},
  {name: "Norway", hello: "Hallo"},
  {name: "Sweden", hello: "Hallå"},
  {name: "Poland", hello: "Cześć"},
  {name: "Romania", hello: "Salut"},
  {name: "Slovenia", hello: "Živjo"},
  {name: "Georgia", hello: "Komentari"},
  {name: "Albania ", hello: "Përshëndetje"},
  {name: "Armenia", hello: "Barev Dzez"},
  {name: "Macedonia", hello: "Zdravo"},
  {name: "Luxembourg", hello: "Moïen"},
  {name: "Czech Republic", hello: "Ahoj"},
  {name: "Bosnia", hello: "Dobar dan"},
  {name: "Serbia", hello: "Zdravo"},
  {name: "Croatia", hello: "Bok"},
  {name: "Malta ", hello:"Bongu"},
  {name: "Turkey", hello: "Merhaba"},
  {name: "Russia", hello: "Zdravstvuyte"},
  {name: "China", hello: "Ni hao"},
  {name: "Japan", hello: "Kon'nichiwa"},
  {name: "Korea", hello: "Yeoboseyo"},
  {name: "Vietnam", hello: "Xin chào"},
  {name: "South Africa", hello: "Sawubona"},
  {name: "Thailand", hello: "S̄wạs̄dī"},
  {name: "Myanmar", hello: "Haallo"},
  {name: "Philippines", hello: "Kamusta"},
  {name: "Indonesia", hello: "Halo"},
  {name: "Nepal", hello: "Namastē"},
  {name: "Zimbabwe", hello: "Mhoro"},
  {name: "Sri Lanka", hello: "Vaṇakkam"},
  {name: "Brazil", hello: "Olá"},
  {name: "Argentina", hello: "Hola"},
  {name: "Nepal", hello: "Namastē"},
  {name: "Mexico", hello: "Hola"},
  {name: "United States of America", hello: "Hello"},
  {name: "Canada", hello: "Hello"},
  {name: "Australia", hello: "G'Day"},
  {name: "Fiji", hello: "Bula"}
]);
