use hello_world;
db.dropDatabase();

db.hellos.insertMany([
  {name: "France", hello: "bonjour"},
  {name: "Spain", hello: "hola"},
  {name: "Germany", hello: "guten tag"},
  {name: "Netherlands", hello: "Hallo"},
  {name: "Ukraine", hello: "Dobriy den"},
  {name: "Protugal", hello: "Olá"},
  {name: "Denmark", hello: "Hej"},
  {name: "Estonia", hello: "Tere"},
  {name: "Italy", hello: "Ciao"},
  {name: "Slovakia", hello: "Ahoj"},
  {name: "Bulgaria", hello: "Zdraveĭte"},
  {name: "Iceland", hello: "Góðan dag"},
  {name: "Hungary", hello: "Jó napot"},
  {name: "Greece", hello: "Geia sas"},
  {name: "Lithuania", hello: "Sveiki"},
  {name: "Finland", hello: "Hei"},
  {name: "Norway", hello: "Hallo"},
  {name: "Sweden", hello: "Hallå"},
  {name: "Poland", hello: "Cześć"},
  {name: "Romania", hello: "Salut"},
  {name: "Slovenia", hello: "Živjo"},
  {name: "Georgia", hello: "Komentari"},
  {name: "Albania ", hello: "Përshëndetje"},
  {name: "Armenia", hello: "Barev Dzez"},
  {name: "Macedonia", hello: "Zdravo"},
  {name: "Luxembourg", hello: "Moïen"},
  {name: "Czech Republic", hello: "Ahoj"},
  {name: "Bosnia", hello: "Dobar dan"},
  {name: "Serbia", hello: "Zdravo"},
  {name: "Croatia", hello: "Bok"},
  {name: "Malta ", hello:"Bongu"},
  {name: "Turkey", hello: "Merhaba"},
  {name: "Russia", hello: "Zdravstvuyte"},
  {name: "Belarus", hello: "Zdravstvujtie"},
]);
